### ISSUE TITLE
In version 1.2 pause() is named incorrectly because it toggles mute

### ISSUE THREAD

**Issue by Thynix** [sparkfun/Qwiic_MP3_Trigger#6]
Thoughts on naming it `toggleMute()` instead?

These might be better suited to email, but some questions:

* Are the chips still bugged as documented in a5737d1204efccbb310852489c00bf206740246a?
* I take it they aren't programmable then to fix it?
* Does the supplier know about the problem?

**Comment by nseidle** [comment]
> Thoughts on naming it toggleMute() instead?

Sure - that would probably have made it more readable.

> Are the chips still bugged as documented in https://github.com/sparkfun/Qwiic_MP3_Trigger/commit/a5737d1204efccbb310852489c00bf206740246a?

Yup.

> I take it they aren't programmable then to fix it?

I suspect the supplier could reprogram the devices but they are unwilling to admit the issue or provide support.

> Does the supplier know about the problem?

Oh yes. That's why we have dropped them as a supplier.

v1.2 of the firmware should take care of the issue. Please let us know if you find anything awry.
